### ISSUE TITLE
V2 Checklist

### ISSUE THREAD

**Issue by aosasona** [aosasona/mirror#10]
The #4 changes are sort of worthy of being a V2 release, so time to make it that since it is a very major change.

- [x] Move current V1 to an archive branch
- [x] Move development to main branch
- [x] Scrap current README and put in warning
- [x] Add CHANGELOG.md file
- [x] Update documentation
- [x] Better & clearer errors
- [x] Add new project image
- [x] Add examples

# Other planned features
- [x] Warn about duplicates
- [x] Validate targets before attempting generation
- [x] Support hooks (pre-gen/post-parse hooks)
- [ ] #1

**Comment by aosasona** [comment]
There is a known regression regarding unexported fields, this should be revisited later.
