### ISSUE TITLE
feat: add alternative backends

### ISSUE THREAD

**Issue by aosasona** [aosasona/mirror#4]
I need to re-architect mirror to support other languages like Swift for example. Most parts will remain the same except the current implementation will now become a `backend` and we will do transformations from the (new) virtual AST we will generate during parsing (we have most of this work already in our parsing stage I believe)

## Sub-tasks
> [!NOTE]
> These subtasks are not in any particular order and this is a mostly incomplete list right now
- [x] Add new types
- [x] Refactor to support generators
- [x] Add new Target interface
- [x] Accommodate for new targets in config
- [x] Implement new parser to spit out items
- [x] Handle Uintptr, Complex32|64 and Func this time
- [ ] Implement target backends
- [ ] Update documentation and description(s)
> The chan type cannot be represented in other languages anyway so we will skip that, also the complex numbers and uintptr are rarely used, with the uintptr being advised against even.

## Targets
- [ ] TypeScript
- [ ] Swift
- [ ] Gleam

## Types
- [x] Integer (int8, int16, int32, int64, uint8. uint16, uint32, uint64, int, uint) - no support for complex64 and complex 128 yet
- [x] String
- [x] Boolean
- [x] Map
- [x] Struct
- [x] Array
- [x] Slice
- [x] Pointer
   - [x] Scalar
   - [x] &Struct
   - [x] &Array
   - [x] &Slice
- [x] Func
~Complex64|Complex128~
~Uintptr~

**Comment by aosasona** [comment]
- Rewrite the entry point and targets to take options for each targets
- Remove the general `Config` struct
